// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using family_tree.Data;

#nullable disable

namespace family_tree.Migrations
{
    [DbContext(typeof(FamilyTreeDbContext))]
    [Migration("20260930103358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("family_tree.Entities.FamilyTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_family_trees");

                    b.ToTable("family_trees", (string)null);
                });

            modelBuilder.Entity("family_tree.Entities.ParentChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer")
                        .HasColumnName("child_id");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_parent_children");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_parent_children_child_id");

                    b.HasIndex("ParentId", "ChildId")
                        .IsUnique()
                        .HasDatabaseName("ix_parent_children_parent_id_child_id");

                    b.ToTable("parent_children", (string)null);
                });

            modelBuilder.Entity("family_tree.Entities.Partnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EndReason")
                        .HasColumnType("text")
                        .HasColumnName("end_reason");

                    b.Property<int>("Person1Id")
                        .HasColumnType("integer")
                        .HasColumnName("person1_id");

                    b.Property<int>("Person2Id")
                        .HasColumnType("integer")
                        .HasColumnName("person2_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_partnerships");

                    b.HasIndex("Person1Id")
                        .HasDatabaseName("ix_partnerships_person1id");

                    b.HasIndex("Person2Id")
                        .HasDatabaseName("ix_partnerships_person2id");

                    b.ToTable("partnerships", (string)null);
                });

            modelBuilder.Entity("family_tree.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthPlace")
                        .HasColumnType("text")
                        .HasColumnName("birth_place");

                    b.Property<string>("BirthSurname")
                        .HasColumnType("text")
                        .HasColumnName("birth_surname");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("given_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer")
                        .HasColumnName("tree_id");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasIndex("TreeId")
                        .HasDatabaseName("ix_people_tree_id");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("family_tree.Entities.ParentChild", b =>
                {
                    b.HasOne("family_tree.Entities.Person", "Child")
                        .WithMany("ParentEdges")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parent_children_people_child_id");

                    b.HasOne("family_tree.Entities.Person", "Parent")
                        .WithMany("ChildEdges")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parent_children_people_parent_id");

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("family_tree.Entities.Partnership", b =>
                {
                    b.HasOne("family_tree.Entities.Person", "Person1")
                        .WithMany()
                        .HasForeignKey("Person1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partnerships_people_person1id");

                    b.HasOne("family_tree.Entities.Person", "Person2")
                        .WithMany()
                        .HasForeignKey("Person2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_partnerships_people_person2id");

                    b.OwnsOne("family_tree.Entities.FuzzyDate", "EndDate", b1 =>
                        {
                            b1.Property<int>("PartnershipId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("end_date_precision");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("end_date_value");

                            b1.HasKey("PartnershipId");

                            b1.ToTable("partnerships");

                            b1.WithOwner()
                                .HasForeignKey("PartnershipId")
                                .HasConstraintName("fk_partnerships_partnerships_id");
                        });

                    b.OwnsOne("family_tree.Entities.FuzzyDate", "StartDate", b1 =>
                        {
                            b1.Property<int>("PartnershipId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("start_date_precision");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("start_date_value");

                            b1.HasKey("PartnershipId");

                            b1.ToTable("partnerships");

                            b1.WithOwner()
                                .HasForeignKey("PartnershipId")
                                .HasConstraintName("fk_partnerships_partnerships_id");
                        });

                    b.Navigation("EndDate");

                    b.Navigation("Person1");

                    b.Navigation("Person2");

                    b.Navigation("StartDate");
                });

            modelBuilder.Entity("family_tree.Entities.Person", b =>
                {
                    b.HasOne("family_tree.Entities.FamilyTree", "Tree")
                        .WithMany("People")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_people_family_trees_tree_id");

                    b.OwnsOne("family_tree.Entities.FuzzyDate", "BirthDate", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("birth_date_precision");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("birth_date_value");

                            b1.HasKey("PersonId");

                            b1.ToTable("people");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_people_people_id");
                        });

                    b.OwnsOne("family_tree.Entities.FuzzyDate", "DeathDate", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("death_date_precision");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("date")
                                .HasColumnName("death_date_value");

                            b1.HasKey("PersonId");

                            b1.ToTable("people");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_people_people_id");
                        });

                    b.Navigation("BirthDate");

                    b.Navigation("DeathDate");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("family_tree.Entities.FamilyTree", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("family_tree.Entities.Person", b =>
                {
                    b.Navigation("ChildEdges");

                    b.Navigation("ParentEdges");
                });
#pragma warning restore 612, 618
        }
    }
}
